import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

export const metadata: Metadata = {
  title: "Shadamon Admin",
  description: "Generated by Shadamon Admin",
};

import { SettingsProvider } from "./context/SettingsContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <SettingsProvider>
          <Toaster position="top-right" />
          {children}
        </SettingsProvider>
      </body>
    </html>
  );
}
